"""empty message

Revision ID: 80f73f7ab46e
Revises: b9fdafb786bb
Create Date: 2017-07-23 09:58:34.759073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80f73f7ab46e'
down_revision = 'b9fdafb786bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_index(op.f('ix_admins_eMail'), 'admins', ['eMail'], unique=True)
    op.create_index(op.f('ix_admins_firstName'), 'admins', ['firstName'], unique=False)
    op.create_index(op.f('ix_admins_lastName'), 'admins', ['lastName'], unique=False)
    op.create_index(op.f('ix_admins_userName'), 'admins', ['userName'], unique=True)
    op.drop_index('ix_admins_eMail', table_name='admins')
    op.drop_index('ix_admins_firstName', table_name='admins')
    op.drop_index('ix_admins_lastName', table_name='admins')
    op.drop_index('ix_admins_userName', table_name='admins')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_admins_userName', 'admins', ['userName'], unique=True)
    op.create_index('ix_admins_lastName', 'admins', ['lastName'], unique=False)
    op.create_index('ix_admins_firstName', 'admins', ['firstName'], unique=False)
    op.create_index('ix_admins_eMail', 'admins', ['eMail'], unique=True)
    op.drop_index(op.f('ix_admins_userName'), table_name='admins')
    op.drop_index(op.f('ix_admins_lastName'), table_name='admins')
    op.drop_index(op.f('ix_admins_firstName'), table_name='admins')
    op.drop_index(op.f('ix_admins_eMail'), table_name='admins')
    op.drop_table('phones')
    # ### end Alembic commands ###
