"""empty message

Revision ID: c61ac00a5664
Revises: 
Create Date: 2017-07-30 06:35:29.999136

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c61ac00a5664'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admins')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('eMail', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('userName', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('firstName', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('lastName', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('passwordHash', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('isSuperAdmin', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
